name: Test code

on:
  workflow_call:

env:
  PYTHON_VERSION: "3.11.0"

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pdm
        uses: thiagola92/setup-pdm@rm-install-output
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          enable-pep582: true
          remove-install-output: true

      - name: Format and test code
        run: |
          pdm install
          pdm run black
          pdm run isort
          pdm run unittest

      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Format code
          default_author: github_actions
