name: Apply Terraform

on:
  workflow_call:
    secrets:
      gh_token:
        required: true
      machine_ip:
        required: false
      vault_token:
        required: false
      mongo_user:
        required: false
      mongo_pass:
        required: false
      meili_key:
        required: false
      influx_user:
        required: false
      influx_pass:
        required: false
      rabbit_user:
        required: false
      rabbit_pass:
        required: false

jobs:
  apply:
    runs-on: self-hosted
    env:
      GITHUB_TOKEN: ${{ secrets.gh_token }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Apply Terraform
        uses: dflook/terraform-apply@v1
        with:
          auto_approve: true
          variables: |
            gh_token = "${{ secrets.gh_token }}"
            machine_ip = "${{ secrets.machine_ip }}"
            vault_token = "${{ secrets.vault_token }}"
            mongo_user = "${{ secrets.mongo_user }}"
            mongo_pass = "${{ secrets.mongo_pass }}"
            meili_key = "${{ secrets.meili_key }}"
            influx_user = "${{ secrets.influx_user }}"
            influx_pass = "${{ secrets.influx_pass }}"
            rabbit_user = "${{ secrets.rabbit_user }}"
            rabbit_pass = "${{ secrets.rabbit_pass }}"

      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
            
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Save changes
          default_author: github_actions
          add: '--update'
          pull: '--ff'
